name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0
        pip install cython==0.29.36

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libffi-dev libssl-dev zlib1g-dev
        sudo apt-get install -y openjdk-17-jdk

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/android-sdk
        rm commandlinetools.zip
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.0" "platforms;android-33" "platform-tools"
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        cd BratvaGame
        buildozer init

   name: Configure buildozer.spec
  run: |
    cd BratvaGame
    sed -i 's/title = My Application/title = Bratva 90s/' buildozer.spec
    sed -i 's/package.name = myapp/package.name = bratva/' buildozer.spec
    sed -i 's/package.domain = org.test/package.domain = org.bratva/' buildozer.spec
    sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,mp3/' buildozer.spec
    sed -i 's/requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec
    sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
    sed -i 's/android.api = 31/android.api = 33/' buildozer.spec
    sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
    sed -i 's/#icon =/icon = images\/icon.png/' buildozer.spec
    sed -i 's/#android.sdk_path =/android.sdk_path = \/root\/android-sdk/' buildozer.spec

    - name: Build APK
      run: |
        cd BratvaGame
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: BratvaGame/bin/*.apk
